name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
#   access:
#     uses: githubuserdemo/hello-world-composite-run-steps-action/.github/workflows/terraform.yml@main
#     with:
#       username: mona
#     secrets:
#       TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
#       - uses: pwechuli/myaction@main
      - uses: githubuserdemo/hello-world-composite-run-steps-action@main
      - uses: actions/checkout@v2
        with:
          repository: githubuserdemo/hello-world-composite-run-steps-action
      - name: Log directory
        run: ls

